//! lava-google — autogenerated typed resource catalog for the
//! google terraform provider. Mirrors pangea-google.

#![allow(clippy::module_name_repetitions)]

pub const RESOURCES_DIR: &str = "resources";

pub const RESOURCES: &[&str] = &[
    "google_compute_network",
    "google_compute_subnetwork",
    "google_container_cluster",
    "google_project_iam_binding",
    "google_service_account",
    "google_storage_bucket",];

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn every_registered_resource_has_a_tlisp_file() {
        let base = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(RESOURCES_DIR);
        for name in RESOURCES {
            let p = base.join(format!("{name}.tlisp"));
            assert!(p.exists(), "missing typed shape on disk: {}", p.display());
        }
    }
    #[test]
    fn index_tlisp_exists() {
        let base = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(RESOURCES_DIR);
        assert!(base.join("_index.tlisp").exists());
    }
    #[test]
    fn schema_json_present() {
        let base = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        assert!(base.join("schema.json").exists());
    }
    #[test]
    fn at_least_one_resource_registered() {
        assert!(!RESOURCES.is_empty());
    }
}
